export const REQUESTS_LOADING = "REQUESTS_LOADING";
export const REQUESTS_OK = "REQUESTS_OK";
export const REQUESTS_X = "REQUESTS_X";
export const ADDED_REQUEST_OK = "ADDED_REQUEST_OK";
export const ADDED_REQUEST_X = "ADDED_REQUEST_X"
